### PR TITLE
Support conditional export resolution with custom resolver

### PR DESCRIPTION
**Pull request by nick-klaviyo**
Support resolution of conditional export packages with customer resolver. This change implements the solution described in https://github.com/patriksimek/vm2/issues/504

### CODE REVIEW

**Comment by XmiliaH** [comment]
Thank you for the PR. Could you check that `npm test` is succeeding. Seems like `eslint` wants some changes.
Furthermore, it would be nice to edit the `resolve` method in `index.d.ts` to also allow to return the object.

**Comment by nick-klaviyo** [comment]
> Thank you for the PR. Could you check that `npm test` is succeeding. Seems like `eslint` wants some changes. Furthermore, it would be nice to edit the `resolve` method in `index.d.ts` to also allow to return the object.

Thanks - I've added the missing comma that was failing `eslint` and updated `index.d.ts` - let me know if that additional return type is what you were thinking.

Also: is there additional configuration I need to do locally in order to run `eslint`? If I run the `pretest` npm script locally I get thousands of errors across all the project files. Something must be off with my settings 🤔

**Comment by XmiliaH** [comment]
Seems good to me now. Thank you.

**Comment by nick-klaviyo** [comment]
Thank you!

**Comment by nick-klaviyo** [comment]
@XmiliaH Do you know when this will be released?

**Comment by XmiliaH** [comment]
I am busy over the weekend. Will try to do it on Monday.

**Comment by XmiliaH** [comment]
The new version is released

**Comment by nick-klaviyo** [comment]
> The new version is released

Thanks!

**Pull request merged**
