### PR TITLE
Transform option to support custom language

### PR DESCRIPTION
**Pull request by dangreen**

### CODE REVIEW

**Comment by patriksimek** [comment]
Thanks for the contribution, could you please add at least one simple test suite?

**Comment by dangreen** [comment]
```js
import { NodeVM }    from 'vm2';
import { transform } from 'babel-core';

var vm = new NodeVM({
    compile(code) {
        return transform(code, babelConfig).code;
    }
});

vm.run(`
    import Test from './test';
    
    console.log(\`ES6 in vm2!\`);
`);
```

**Comment by dangreen** [comment]
It would be grate if `compile` function will receive file extension as second argument. You can add this feature yourself or I do it, but later.

**Comment by patriksimek** [comment]
Thanks for you effort, closing this one as there's new major version comming with a lot of changes.

**Comment by oscartbeaumont** [comment]
How can this be achieved with the new version?

**Comment by XmiliaH** [comment]
The option was renamed to `compiler`. So
```JS
var vm = new NodeVM({
    compiler(code) {
        return transform(code, babelConfig).code;
    }
});
```
should work.

**Pull request closed without merging**
