### PR TITLE
feat: add microtaskMode support

### PR DESCRIPTION
**Pull request by Raoul1996**
In Node v14.06, official `vm` module add run-after-evaluate microtask mode (By Anna Henningsen, [PR](https://github.com/nodejs/node/pull/34023))

This allows timeouts to apply to e.g. Promises and async functions from code running inside of vm.Contexts, by giving the Context its own microtasks queue.

### CODE REVIEW

**Comment by Raoul1996** [comment]
[vm: add run-after-evaluate microtask mode](https://github.com/nodejs/node/pull/34023)

**Comment by Raoul1996** [comment]
@patriksimek

**Comment by Raoul1996** [comment]
@XmiliaH

**Comment by rodrigozr** [comment]
**Highly interested on this**. The addition of microtaskMode in NodeJS v14 solved a major issue with escaping the VM timeout

**Comment by mariusandra** [comment]
I'd be very keen to get this feature into `vm2`. What could I do to help? The PR here seems rather solid...

**Pull request closed without merging**
