### PR TITLE
Add internal to support trusted libs without contextify for class ext…

### PR DESCRIPTION
**Pull request by khoshrou**
I like to extend classes from some trusted base classes
thats not possible right now but if you let us import some trusted libraries without contextify
thats going to be amazing

### CODE REVIEW

**Comment by XmiliaH** [comment]
I'm not going to accept this PR, since it is too easy to use this functionality wrong. You need to check that the host function prototype is not accessible throug property traversel, functions exposed can't throw exceptions and return value could have the same problem. It's just too risky to allow this.

**Comment by khoshrou** [comment]
so is there any way that I can extend from some trusted internal base classes?

**Comment by XmiliaH** [comment]
I wonder if this was fixed by node or v8 at some time since
```JS
const {VM} = require('vm2');
class A {};
const vm = new VM({sandbox:{A}});
const b = vm.run('class B extends A{}; new B()');
console.log(b instanceof A);
```
works for me (tested on node v12.16.1) or I just don't understand the problem.

**Comment by khoshrou** [comment]
Right to the point
- Your sample returns false if you use NodeVM
- and the problem is B's methods are not accessible
```js
const { VM } = require('vm2');
class A {
	callA() {
		return 'From A';
	}
};
const vm = new VM({ sandbox: { A } });
const b = vm.run(`class B extends A{
	callB() {
		return 'From B';
	}
}; 
new B()
`);
console.log(b instanceof A);
console.log(b.callA()); // works
console.log(b.callB()); // raises : TypeError: b.callB is not a function
```

**Comment by XmiliaH** [comment]
This seems to be a problem with the proxy construct handler since it discards newTarget. If newTarget is used this works (but b instanceof A if false). Need to look into that a bit more if it is safe to use newTarget and if there are other problems with that.

**Comment by khoshrou** [comment]
Let me know if there is a fix for this. meanwhile if I use my changes in this pull request and just add safe trusted base classes do you think I am still exposed to security vulnerabilities?

**Comment by XmiliaH** [comment]
If you don't Object.setPrototypeOf(..., null) every leaf object and every function has a wildcard catch and returns a primitive or rethrows null and the return from every accessible function is ether a object where every leaf is Object.setPrototypeOf(..., null) or a primitive it might be ok, if that is not the case there is likely a way out. However, following this does not guarantee there is no wayout.

To be clear, I don't think this is a good idea, since it is too easy to do it wrong.

**Comment by khoshrou** [comment]
You are right, so let me know if there is a fix for this
And thanks for the awesome library

**Pull request closed without merging**
