### PR TITLE
Add support for custom source file extensions

### PR DESCRIPTION
**Pull request by orta**
I'd like to be able to support TypeScript today, but this feature could mean the special-casing of coffeescript support could be removed as there's enough here to allow anyone to add that support in their own apps easily.

### CODE REVIEW

**Comment by Igmat** [comment]
I'm not sure that it would be enough for additional type of transpilers, but it's a good start.
I tried to achieve TS support inside vm by calling [pirates](https://github.com/ariporad/pirates) inside `NodeVM` but it seems that `require` and `module` can't be affected by script code.

**Comment by orta** [comment]
Good call, I did end up using this in danger-js, but I think moving to pirates is probably what I want to do in the future, thanks!

**Comment by orta** [comment]
Merging, it's been used in danger in prod for the best part of a year

**Comment by hmagrini** [comment]
@orta could you restore the `custom_files` branch? it seems that DangerJS is [using that branch as dependency](https://github.com/danger/danger-js/blob/master/package.json#L139), thus all installations that depend on DangerJS seem to be failing to install.

**Comment by orta** [comment]
Heh, I have told that auto delete branches, that should keep it running 👍

**Comment by hmagrini** [comment]
awesome, thanks for the quick response!

**Comment by michaeljacobdavis** [comment]
@patriksimek Would it be possible to do a publish of vm2 that includes this?

**Comment by patriksimek** [comment]
@michaeljacobdavis I have just added @orta into npm maintainers. I'm temporarily unavailable to maintain the project. Thank you!

**Comment by orta** [comment]
Ace, thanks @patriksimek

**Comment by orta** [comment]
Hah, sorry about all ^ 🍡

**Pull request merged**
