### PR TITLE
Overhaul NodeVM.

### PR DESCRIPTION
**Pull request by XmiliaH**
Should fix https://github.com/patriksimek/vm2/issues/276.
Tried to make NodeVM more secure by catching more errors that could be leaked from host.

### CODE REVIEW

**Comment by patriksimek** [comment]
Thanks @XmiliaH , this looks awesome! I'll take a deeper look asap.

**Comment by XmiliaH** [comment]
@patriksimek This should have been included in 3.9.1 since it fixes the breakout in the NodeVM.

**Comment by patriksimek** [comment]
@XmiliaH My goal was to publish the fix for #274 asap. I'm Sorry I didn't include this one, but I wanted to review it before I merge it and time is my biggest enemy atm :(

**Comment by patriksimek** [comment]
Can you please share your npm username? I'll grant you access to publishing.

**Comment by XmiliaH** [comment]
Just created the account, [xmilia](https://www.npmjs.com/~xmilia).

**Pull request merged**
